# Generated by Django 2.2.6 on 2021-02-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer', '0002_auto_20210203_0847'),
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('i', 'invoice')], default='i', max_length=2)),
                ('document_type_version', models.CharField(choices=[('1.0', '1.0')], default='1.0', max_length=8)),
                ('date_time_issued', models.DateTimeField(auto_now_add=True)),
                ('internal_id', models.CharField(max_length=50)),
                ('purchase_order_reference', models.CharField(max_length=50)),
                ('purchase_order_description', models.CharField(max_length=100)),
                ('sales_order_reference', models.CharField(max_length=50)),
                ('sales_order_description', models.CharField(max_length=100)),
                ('proforma_invoice_number', models.CharField(max_length=50)),
                ('total_sales_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('total_discount_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('extra_discount_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('total_items_discount_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('signature', models.TextField()),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Reciever')),
                ('taxpayer_activity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.ActivityType')),
            ],
        ),
    ]
