# Generated by Django 2.2.6 on 2021-03-02 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0001_initial'),
        ('taxManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 12, 54, 36, 461685), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceheader',
            unique_together={('issuer', 'internal_id')},
        ),
    ]
