# Generated by Django 2.2.6 on 2021-03-11 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 13, 36, 21, 515520)),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='currency_sold',
            field=models.ForeignKey(default='EGP', on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency', verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
