# Generated by Django 2.2.6 on 2021-02-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default='2021-02-08T10:06:23', null=True),
        ),
    ]
