# Generated by Django 2.2.6 on 2021-02-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0007_auto_20210207_1324'),
        ('taxManagement', '0002_maintable_signature_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='issuer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_address', to='issuer.Address'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='receiver_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_address', to='issuer.Address'),
        ),
    ]
