# Generated by Django 2.2.6 on 2021-02-25 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0002_auto_20210224_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 13, 22, 36, 81377), null=True),
        ),
    ]
