# Generated by Django 2.2.6 on 2021-04-22 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0002_auto_20210412_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 11, 28, 17, 792194)),
        ),
    ]
