# Generated by Django 2.2.6 on 2021-03-01 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0002_auto_20210301_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 1, 11, 37, 26, 841557), null=True),
        ),
    ]
