# Generated by Django 2.2.6 on 2021-03-11 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0002_auto_20210311_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='currencySold',
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 13, 53, 59, 818667)),
        ),
    ]
