# Generated by Django 2.2.6 on 2021-02-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0002_auto_20210208_1006'),
        ('taxManagement', '0002_maintable_signature_value'),
    ]

    operations = [
    ]
