# Generated by Django 2.2.6 on 2021-02-16 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20210214_1453'),
        ('taxManagement', '0003_auto_20210214_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 11, 31, 55, 303582), null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='document_type',
            field=models.CharField(blank=True, choices=[('I', 'I')], default='I', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='extra_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_items_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_sales_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, help_text='Optional: amount of discount provided to customer for this item. Should be smaller or equal to value Total. If percentage specified should be valid amount calculated from total by applying discount percentage. ', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='itemsDiscount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, help_text='Non-taxable items discount.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='netTotal',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, help_text='Total amount for the invoice line after applying discount.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Optional: discount percentage rate applied. Must be from 0 to 100.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='salesTotal',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, help_text='Total amount for the invoice line considering quantity and unit price in EGP (with excluded factory amounts if they are present for specific types in documents).', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, help_text='Total amount for the invoice line after adding all pricing items, taxes, removing discounts.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='totalTaxableFees',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, help_text='Total amount of additional taxable fees to be used in final tax calculation.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='valueDifference',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, help_text='Value difference when selling goods already taxed (accepts +/- numbers), e.g., factory value based.', max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='HeaderTaxTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxManagement.InvoiceHeader')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codes.TaxTypes')),
            ],
        ),
    ]
