# Generated by Django 2.2.6 on 2021-03-16 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0003_auto_20210315_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='invoice_status',
            field=models.CharField(default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 9, 10, 51, 933522)),
        ),
    ]
