# Generated by Django 2.2.6 on 2021-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0003_maintable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
