# Generated by Django 2.2.6 on 2021-02-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0003_auto_20210207_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceheader',
            name='signature',
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(blank=True, max_length=20, null=True)),
                ('signature_value', models.TextField(blank=True, null=True)),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxManagement.InvoiceHeader')),
            ],
        ),
    ]
