# Generated by Django 2.2.6 on 2021-05-04 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0003_auto_20210422_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 12, 39, 0, 155614)),
        ),
        migrations.AlterField(
            model_name='taxline',
            name='subType',
            field=models.ForeignKey(default='Ent01', on_delete=django.db.models.deletion.CASCADE, to='codes.TaxSubtypes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxline',
            name='taxType',
            field=models.ForeignKey(default='T1', on_delete=django.db.models.deletion.CASCADE, to='codes.TaxTypes'),
            preserve_default=False,
        ),
    ]
