# Generated by Django 2.2.6 on 2021-02-09 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0003_merge_20210209_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subm_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('subm_uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('document_count', models.IntegerField(blank=True, null=True)),
                ('date_time_received', models.DateTimeField(blank=True, null=True)),
                ('over_all_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 9, 10, 44, 20, 147541), null=True),
        ),
    ]
