# Generated by Django 2.2.6 on 2021-04-28 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0003_auto_20210422_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 11, 25, 56, 857831)),
        ),
    ]
