# Generated by Django 2.2.6 on 2021-02-16 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0003_auto_20210216_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 15, 34, 21, 372281), null=True),
        ),
    ]
