# Generated by Django 2.2.6 on 2021-04-28 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0004_auto_20210428_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 12, 50, 49, 486294)),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='itemType',
            field=models.CharField(choices=[('GS1', 'GS1'), ('GPS', 'GPS'), ('EGS', 'EGS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unitType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='codes.UnitType'),
        ),
    ]
