# Generated by Django 2.2.6 on 2021-02-10 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0004_auto_20210210_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxManagement.InvoiceHeader'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 9, 57, 32, 618589), null=True),
        ),
    ]
