# Generated by Django 2.2.6 on 2021-03-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0004_auto_20210316_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 12, 33, 54, 817390)),
        ),
    ]
