# Generated by Django 2.2.6 on 2021-05-04 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0004_auto_20210504_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 12, 54, 13, 313908)),
        ),
        migrations.AlterField(
            model_name='taxline',
            name='subType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codes.TaxSubtypes'),
        ),
        migrations.AlterField(
            model_name='taxline',
            name='taxType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codes.TaxTypes'),
        ),
    ]
