# Generated by Django 2.2.6 on 2021-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0004_auto_20210203_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
