# Generated by Django 2.2.6 on 2021-05-04 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0005_auto_20210504_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 13, 1, 52, 918302)),
        ),
    ]
