# Generated by Django 2.2.6 on 2021-03-11 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0005_auto_20210310_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 12, 18, 36, 995662)),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='document_type',
            field=models.CharField(choices=[('I', 'Invoice'), ('C', 'Credit Memo'), ('D', 'Debit Memo')], default='I', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='document_type_version',
            field=models.CharField(choices=[('1.0', '1.0'), ('0.9', '0.9')], default='1.0', max_length=8),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='internal_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issuer.Receiver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='taxpayer_activity_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codes.ActivityType'),
            preserve_default=False,
        ),
    ]
