# Generated by Django 2.2.6 on 2021-05-05 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0006_auto_20210504_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 10, 40, 9, 827826)),
        ),
    ]
