# Generated by Django 2.2.6 on 2021-03-11 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('taxManagement', '0007_auto_20210311_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='currency_sold',
            field=models.ForeignKey(default='EGP', on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency', verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 13, 55, 42, 83445)),
        ),
    ]
