# Generated by Django 2.2.6 on 2021-05-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0005_auto_20210428_1250'),
        ('taxManagement', '0007_auto_20210428_1456'),
        ('taxManagement', '0005_auto_20210506_1207'),
        ('taxManagement', '0004_auto_20210428_1332'),
        ('taxManagement', '0007_auto_20210505_1040'),
    ]

    operations = [
    ]
