# Generated by Django 2.2.6 on 2021-03-17 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0008_auto_20210317_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 11, 25, 33, 57864)),
        ),
    ]
