# Generated by Django 2.2.6 on 2021-03-11 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0010_auto_20210311_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 14, 4, 29, 427535)),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='internalCode',
            field=models.CharField(default=1, help_text='Optional: Internal code used for the product being sold – can be used to simplify references back to existing solution.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='itemCode',
            field=models.CharField(default=1, help_text='Must be of GS1 code', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='itemType',
            field=models.CharField(default=1, help_text='Must be of GPC format', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Optional: discount percentage rate applied. Must be from 0 to 100.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unitType',
            field=models.CharField(default=1, help_text='A code from unitype table', max_length=50),
            preserve_default=False,
        ),
    ]
