# Generated by Django 2.2.6 on 2021-05-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0010_auto_20210506_1650'),
        ('taxManagement', '0011_auto_20210509_1142'),
    ]

    operations = [
    ]
