# Generated by Django 2.2.6 on 2021-05-17 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0002_issueractivitycode'),
        ('taxManagement', '0012_merge_20210510_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='date_time_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 18, 34, 769084)),
        ),
        migrations.CreateModel(
            name='InvoiceImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('I', 'Invoice'), ('C', 'Credit Memo'), ('D', 'Debit Memo')], default='I', max_length=2)),
                ('document_type_version', models.CharField(choices=[('1.0', '1.0'), ('0.9', '0.9')], default='1.0', max_length=8)),
                ('date_time_issued', models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 18, 34, 774060))),
                ('internal_id', models.CharField(max_length=50)),
                ('purchase_order_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_order_description', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_order_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_order_description', models.CharField(blank=True, max_length=100, null=True)),
                ('proforma_invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True)),
                ('total_items_discount_amount', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=20, null=True)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
            ],
        ),
    ]
