# Generated by Django 2.2.6 on 2021-02-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
        ('issuer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuertax',
            name='tax_type',
        ),
        migrations.AddField(
            model_name='issuertax',
            name='tax_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_tax_type', to='codes.TaxSubtypes'),
        ),
    ]
