# Generated by Django 2.2.6 on 2021-03-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='issuer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer'),
            preserve_default=False,
        ),
    ]
