# Generated by Django 2.2.6 on 2021-02-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0002_auto_20210203_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'business'), ('P', 'natural person'), ('F', 'foreigner')], default='B', max_length=8)),
                ('reg_num', models.CharField(max_length=8, verbose_name='reg_number')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='reciever name')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reciever',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='address',
            name='reciever',
        ),
        migrations.AlterField(
            model_name='address',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_addresses', to='issuer.Issuer'),
        ),
    ]
