# Generated by Django 2.2.6 on 2021-02-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
        ('issuer', '0002_auto_20210224_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuertax',
            name='tax_sub_type',
        ),
        migrations.AddField(
            model_name='issuertax',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_tax_type', to='codes.TaxTypes'),
        ),
        migrations.CreateModel(
            name='IssuerOracleDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('port_number', models.CharField(max_length=10)),
                ('service_number', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.Issuer')),
            ],
        ),
    ]
