# Generated by Django 2.2.6 on 2021-02-16 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20210214_1453'),
        ('issuer', '0003_auto_20210214_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='activity_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codes.ActivityType'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='reg_num',
            field=models.CharField(max_length=20, verbose_name='reg_number'),
        ),
        migrations.AlterField(
            model_name='issuertax',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 9, 31, 55, 294585, tzinfo=utc), null=True),
        ),
    ]
