# Generated by Django 2.2.6 on 2021-02-03 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxManagement', '0002_auto_20210203_1009'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0003_auto_20210203_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reciever',
        ),
        migrations.AddField(
            model_name='receiver',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receiver_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiver',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_addresses', to='issuer.Receiver'),
        ),
    ]
