# Generated by Django 2.2.6 on 2021-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0003_auto_20210228_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueroracledb',
            name='database_name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueroracledb',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
