# Generated by Django 2.2.6 on 2021-02-04 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0004_auto_20210204_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuertax',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 4, 14, 34, 41, 886126, tzinfo=utc), null=True),
        ),
    ]
