# Generated by Django 2.2.6 on 2021-02-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0002_auto_20210204_1039'),
        ('issuer', '0004_auto_20210207_1012'),
        ('issuer', '0003_auto_20210208_1006'),
    ]

    operations = [
    ]
