# Generated by Django 2.2.6 on 2021-02-10 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0004_auto_20210210_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuertax',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 10, 9, 57, 32, 609394, tzinfo=utc), null=True),
        ),
    ]
