# Generated by Django 2.2.6 on 2021-02-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0002_auto_20210204_1039'),
        ('issuer', '0004_auto_20210207_1012'),
    ]

    operations = [
    ]
