# Generated by Django 2.2.6 on 2021-02-16 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0004_auto_20210216_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuertax',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 9, 45, 30, 269090, tzinfo=utc), null=True),
        ),
    ]
