# Generated by Django 2.2.6 on 2021-02-16 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0004_auto_20210216_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuertax',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 16, 10, 7, 52, 886260, tzinfo=utc), null=True),
        ),
    ]
