# Generated by Django 2.2.6 on 2021-03-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0004_auto_20210301_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueroracledb',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
