# Generated by Django 2.2.6 on 2021-02-07 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0005_merge_20210207_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuertax',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 13, 13, 12, 218268, tzinfo=utc), null=True),
        ),
    ]
