# Generated by Django 2.2.6 on 2021-02-09 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0005_merge_20210209_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuertax',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 9, 10, 44, 20, 142659, tzinfo=utc), null=True),
        ),
    ]
