# Generated by Django 2.2.6 on 2021-02-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('desc_en', models.CharField(max_length=50)),
                ('desc_ar', models.CharField(max_length=50)),
                ('is_taxable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxSubtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('desc_en', models.CharField(max_length=50)),
                ('desc_ar', models.CharField(max_length=50)),
                ('taxtype_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.TaxTypes')),
            ],
        ),
    ]
