# Generated by Django 2.2.6 on 2021-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtypes',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
