# Generated by Django 2.2.6 on 2021-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_ar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_ar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_ar', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
