# Generated by Django 2.2.6 on 2021-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20210203_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtypes',
            name='is_taxable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
